#if !canImport(ObjectiveC)
import XCTest

extension libusb_swiftTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__libusb_swiftTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(libusb_swiftTests.__allTests__libusb_swiftTests),
    ]
}
#endif
